name: raygun_cli
description: A command-line tool for uploading sourcemaps, managing obfuscation symbols, and tracking deployments in Raygun.com
# Update version in bin/raygun_cli.dart as well
version: 0.0.2
repository: https://github.com/MindscapeHQ/raygun-cli/
homepage: https://raygun.com

executables:
  # Ensures the app is installed as "raygun-cli" and not "raygun_cli"
  raygun-cli: 'raygun_cli'

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  http: ^1.3.0

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.24.0
