name: raygun_cli
description: A command-line tool for uploading sourcemaps, managing obfuscation symbols, and tracking deployments in Raygun.com
# Update version in bin/raygun_cli.dart as well
version: 1.1.0
repository: https://github.com/MindscapeHQ/raygun-cli/
homepage: https://raygun.com

executables:
  # Ensures the app is installed as "raygun-cli" and not "raygun_cli"
  raygun-cli: 'raygun_cli'

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.6.0
  http: ^1.6.0

dev_dependencies:
  lints: ">=4.0.0 <7.0.0"
  test: ^1.28.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
